// This file will export all of the strings that are going to be used in this app
export default {
    Global: 'Global',
    LastUpdatedAt: 'Last Updated at ',
    On: 'on',
    ConfirmeCases: 'Confirmed Cases',
    TotalDeaths: 'Total Deaths',
    ActiveCases: 'Active Cases',
    TotalRecovered: 'Total Recovered',
    MortalityRate: 'Mortality Rate',
    TotalCritical: 'Total Critical',
    TodaysCases: 'Today\'s Cases',
    TodaysDeaths: 'Today\'s Deaths',
    CasesPer1M: 'Cases Per 1M',
    DeathsPer1M: 'Deaths Per 1M',
    TotalTested: 'Total Tested',
    TestsPer1M: 'Tests Per 1M',
    SearchForACountry: 'Search for a country...',
    PrivacyPolicy: 'Privacy Policy',
    TermsOfService: 'Terms and Conditions',
    AboutUs: 'About Us',
}